changelog_type: 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
unlabeled_group_title: 'Unlabeled Changes'
pull_request_title_regex: '^Release'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
group_config:
  - title: Bug Fixes
    labels:
      - bug
      - bugfix
  - title: New Features
    labels:
      - improvements
      - enhancement
      - feature
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc
  - title: Dependencies Updates
    labels:
      - dependency
