---
name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: "renovate[bot]"
          LOG_LEVEL: debug
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: "renovate.json"
